/*
 Generated by typeshare 1.13.4
*/

/** Calendar entity */
export interface Calendar {
	id: Uuid;
	user_id: Uuid;
	name: string;
	color: string;
	sync_token: string;
	ctag: string;
	created_at: DateTime<Utc>;
	updated_at: DateTime<Utc>;
}

/** Event status enumeration */
export enum EventStatus {
	Confirmed = "Confirmed",
	Tentative = "Tentative",
	Cancelled = "Cancelled",
}

/** Event entity */
export interface Event {
	id: Uuid;
	calendar_id: Uuid;
	uid: string;
	summary: string;
	description?: string;
	location?: string;
	start: DateTime<Utc>;
	end: DateTime<Utc>;
	is_all_day: boolean;
	status: EventStatus;
	rrule?: string;
	timezone: string;
	version: number;
	etag: string;
	created_at: DateTime<Utc>;
	updated_at: DateTime<Utc>;
}

/** Attendee role (RFC 5545 ROLE parameter) */
export enum AttendeeRole {
	Organizer = "Organizer",
	Attendee = "Attendee",
}

/** Participation status (RFC 5545 PARTSTAT parameter) */
export enum ParticipationStatus {
	NeedsAction = "NeedsAction",
	Accepted = "Accepted",
	Declined = "Declined",
	Tentative = "Tentative",
}

/** Event attendee with RSVP status */
export interface EventAttendee {
	id: Uuid;
	event_id: Uuid;
	email: string;
	telegram_id: string;
	role: AttendeeRole;
	status: ParticipationStatus;
	created_at: DateTime<Utc>;
	updated_at: DateTime<Utc>;
}

/** User entity */
export interface User {
	id: Uuid;
	telegram_id: string;
	telegram_username?: string;
	timezone: string;
	created_at: DateTime<Utc>;
}

