//! Recurrence rule handling and validation.

use chrono::{DateTime, Utc};
use rrule::{RRuleError, RRuleSet, Tz};

use crate::DomainError;

/// Parse an RFC 5545 RRULE string and validate its format.
pub fn validate_rrule(rrule_str: &str) -> Result<(), DomainError> {
    let full_str = format!("DTSTART:20240101T000000Z\nRRULE:{rrule_str}");

    full_str
        .parse::<RRuleSet>()
        .map_err(|err: RRuleError| DomainError::InvalidRRule(err.to_string()))?;

    Ok(())
}

/// Expand a recurrence rule into UTC occurrence dates within a range.
pub fn expand_rrule(
    rrule_str: &str,
    dtstart: DateTime<Utc>,
    range_start: DateTime<Utc>,
    range_end: DateTime<Utc>,
    max_occurrences: usize,
) -> Result<Vec<DateTime<Utc>>, DomainError> {
    let dtstart_str = dtstart.format("%Y%m%dT%H%M%SZ");
    let full_str = format!("DTSTART:{dtstart_str}\nRRULE:{rrule_str}");

    let rrule_set: RRuleSet = full_str
        .parse()
        .map_err(|err: RRuleError| DomainError::InvalidRRule(err.to_string()))?;

    let rrule_tz = rrule_set.get_dt_start().timezone();
    let search_start = range_start
        .with_timezone(&rrule_tz)
        .checked_sub_signed(chrono::Duration::seconds(1))
        .unwrap_or_else(|| range_start.with_timezone(&rrule_tz));

    let limit = max_occurrences.min(u16::MAX as usize) as u16;
    let occurrences = rrule_set
        .after(search_start)
        .all(limit)
        .dates
        .into_iter()
        .take_while(|date: &DateTime<Tz>| *date <= range_end)
        .map(|date: DateTime<Tz>| date.with_timezone(&Utc))
        .collect();

    Ok(occurrences)
}

/// Return the first `count` occurrences generated by a recurrence rule.
pub fn next_occurrences(
    rrule_str: &str,
    dtstart: DateTime<Utc>,
    count: usize,
) -> Result<Vec<DateTime<Utc>>, DomainError> {
    let dtstart_str = dtstart.format("%Y%m%dT%H%M%SZ");
    let full_str = format!("DTSTART:{dtstart_str}\nRRULE:{rrule_str}");

    let rrule_set: RRuleSet = full_str
        .parse()
        .map_err(|err: RRuleError| DomainError::InvalidRRule(err.to_string()))?;

    let occurrences = rrule_set
        .all(count as u16)
        .dates
        .into_iter()
        .map(|date: DateTime<Tz>| date.with_timezone(&Utc))
        .collect();

    Ok(occurrences)
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{Datelike, TimeZone};

    #[test]
    fn validates_rrule_format() {
        assert!(validate_rrule("FREQ=DAILY;COUNT=5").is_ok());
        assert!(validate_rrule("FREQ=WEEKLY;BYDAY=MO,FR").is_ok());
        assert!(validate_rrule("INVALID=TRUE").is_err());
    }

    #[test]
    fn expands_daily_rrule() {
        let dtstart = Utc.with_ymd_and_hms(2026, 1, 1, 10, 0, 0).unwrap();
        let range_start = Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap();
        let range_end = Utc.with_ymd_and_hms(2026, 1, 5, 0, 0, 0).unwrap();

        let occurrences =
            expand_rrule("FREQ=DAILY;COUNT=3", dtstart, range_start, range_end, 10).unwrap();

        assert_eq!(occurrences.len(), 3);
        assert_eq!(occurrences[0], dtstart);
        assert_eq!(occurrences[1], dtstart + chrono::Duration::days(1));
        assert_eq!(occurrences[2], dtstart + chrono::Duration::days(2));
    }

    #[test]
    fn expands_rrule_inside_requested_range() {
        let dtstart = Utc.with_ymd_and_hms(2026, 1, 1, 10, 0, 0).unwrap();
        let range_start = Utc.with_ymd_and_hms(2026, 1, 4, 0, 0, 0).unwrap();
        let range_end = Utc.with_ymd_and_hms(2026, 1, 6, 0, 0, 0).unwrap();

        let occurrences =
            expand_rrule("FREQ=DAILY;COUNT=10", dtstart, range_start, range_end, 10).unwrap();

        assert_eq!(occurrences.len(), 2);
        assert_eq!(occurrences[0].day(), 4);
        assert_eq!(occurrences[1].day(), 5);
    }

    #[test]
    fn returns_next_occurrences() {
        let dtstart = Utc.with_ymd_and_hms(2026, 1, 1, 10, 0, 0).unwrap();
        let occurrences = next_occurrences("FREQ=DAILY", dtstart, 3).unwrap();

        assert_eq!(occurrences.len(), 3);
        assert_eq!(occurrences[0], dtstart);
        assert_eq!(occurrences[1], dtstart + chrono::Duration::days(1));
        assert_eq!(occurrences[2], dtstart + chrono::Duration::days(2));
    }

    #[test]
    #[ignore]
    fn benchmark_expand_rrule_performance() {
        let dtstart = Utc.with_ymd_and_hms(1900, 1, 1, 0, 0, 0).unwrap();
        let range_start = Utc.with_ymd_and_hms(2024, 1, 1, 0, 0, 0).unwrap();
        let range_end = Utc.with_ymd_and_hms(2024, 1, 2, 0, 0, 0).unwrap();

        let occurrences = expand_rrule("FREQ=DAILY", dtstart, range_start, range_end, 10).unwrap();
        assert!(!occurrences.is_empty());
    }
}
